spring:
  application:
    name: lbs_ch06

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe   # í¬íŠ¸/ì„œë¹„ìŠ¤ëª… ë§ê²Œ ìˆ˜ì •í•˜ì„¸ìš”
    username: C##user1
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none      # create / update / validate / none
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
   init:
     mode: always       # ğŸ’¡ í•­ìƒ data.sql ì‹¤í–‰
     data-locations: classpath:data.sql  # (ì„ íƒ) data.sqlì˜ ìœ„ì¹˜ ì§€ì •
